### ISSUE TITLE
new_scale_*() throws an error in ggplot2 3.5.0

### ISSUE THREAD

**Issue by alhenry** [eliocamp/ggnewscale#64]
The function `new_scale_*()` throws the following error in ggplot2 3.5.0:

```
Error in scale$guide == "none" : 
  comparison (==) is possible only for atomic and list types
```

Presumably this is something related to the [new behaviour](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0/) of guides & scales in ggplot?

**Comment by alhenry** [comment]
I've tested with the latest version of ggplot2 and ggnewscale on CRAN and no longer found the issue. Will close this for now. Sorry for the false alarm!

**Comment by eliocamp** [comment]
Good to know! Do report any other issue, though.

**Comment by bennotkin** [comment]
I continue to have the same error, when I set `guide = guide_colorsteps()`.

Here's a reproducible example:

```
ggplot(mpg) +
  geom_point(aes(x = cty, y = hwy, color = displ)) +
  scale_color_stepsn(
    colors = c("yellow", "red"),
    guide = guide_colorsteps()) +
  ggnewscale::new_scale_color()
# Error in scale$guide == "none" : 
#   comparison (==) is possible only for atomic and list types
```

I don't get the error if I don't include `guide = guide_colorsteps()`[^1], nor if `guide = "legend". Both of the following work:

[^1]: Normally, one wouldn't include `guide = guide_colorsteps()` in `scale_color_stepsn`, as it is the default behavior; however, in my non-reprex usage I sometimes set `guide = "legend"`: `guide = if (diff(lengths(list(params$labels, params$breaks))) == 1) "legend" else guide_colorsteps()`

```
ggplot(mpg) +
  geom_point(aes(x = cty, y = hwy, color = displ)) +
  scale_color_stepsn(colors = c("yellow", "red")) +
  ggnewscale::new_scale_color()

ggplot(mpg) +
  geom_point(aes(x = cty, y = hwy, color = displ)) +
  scale_color_stepsn(
    colors = c("yellow", "red"),
    guide = "legend") +
  ggnewscale::new_scale_color()
```

If, rather than setting the guide in `scale_color_stepsn` but in `guides()`, there is no error with ` ggnewscale::new_scale_color()`, but the guide setting persists after `ggnewscale::new_scale_color()`, and that causes a different error when the guide type is different in the next plot:

```
ggplot(mpg) +
  geom_point(aes(x = cty, y = hwy, color = displ)) +
  scale_color_stepsn(colors = c("yellow", "red")) +
  guides(color = guide_colorsteps()) +
  ggnewscale::new_scale_color() +
  # Shifting x and y so they are obviously separate from previous layer
  geom_point(aes(x = cty + 10, y = 50 - hwy, color = class), shape = 1)
# Error in `parse_binned_breaks()`:
# ! Breaks are not formatted correctly for a bin legend.
# ℹ Use `(<lower>, <upper>]` format to indicate bins.
# Run `rlang::last_trace()` to see where the error occurred.
# Warning message:
# In parse_binned_breaks(scale, breaks) : NAs introduced by coercion
```
