### ISSUE TITLE
new_scale_fill doesn't work with stat_lineribbon

### ISSUE THREAD

**Issue by willgearty** [eliocamp/ggnewscale#9]
This came up in https://github.com/willgearty/deeptime/issues/2. When the user makes their custom plot, it looks fine and uses the specified brewer fill scale:

```r
library(tidyverse)
library(tidybayes)
library(ggnewscale)

tb <- 
  tibble(time = 0:100) %>%
  group_by_all() %>%
  do(tibble(value = rnorm(100, .$time, 10),
            group = sample(1:4, 100, TRUE)))

gg <- 
    tb %>%
    ggplot() +
    stat_lineribbon(aes(x = time, y = value)) +
    scale_x_reverse() +
    coord_cartesian(xlim = c(0, 100), 
                    ylim = range(tb$value),
                    expand = FALSE) +
    scale_fill_brewer()
gg
```
![image](https://user-images.githubusercontent.com/7232514/60389366-f3485b00-9a74-11e9-8e5e-f7ee5d39499c.png)

But just adding `new_scale_fill` after this removes the custom fill scale:
```r
gg <- gg + ggnewscale::new_scale_fill()
gg
```
![image](https://user-images.githubusercontent.com/7232514/60389377-01967700-9a75-11e9-89da-a62ca1132c0a.png)

Further, when I try to add another plot with a different fill scale, I get an error:
```r
gg + geom_point(dat = data.frame(x = runif(100,0,100), y = runif(100,0,100), fill = sample(1:4, 100, replace = TRUE)), aes(x = x, y = y, fill = fill))
Error: Discrete value supplied to continuous scale
```

**Comment by eliocamp** [comment]
Strange! 
I'm away right now, going to see the next solar eclipse, so it'll be a few days untill I can sit and check this bug.

Thanks!

**Comment by eliocamp** [comment]
Ok, I couldn't wait 😂️

I think the problem stems from the strange and non standard (I think!) way in which `stat_lineribbon()` handles computed aesthetics [here](https://github.com/mjskay/tidybayes/blob/a85c7c164c21eb9120d7fab6b1501af19e93b782/R/stat_lineribbon.R#L102). I'm not sure why is done that way since the reason given in [this](https://github.com/mjskay/tidybayes/blob/a85c7c164c21eb9120d7fab6b1501af19e93b782/R/geom.R#L12) comment doesn't make sense to me. Computed aesthetics are accessible in the `default_aes` component (as in [here](https://github.com/eliocamp/metR/blob/ddb55c363238511d1da9f584f5a6b9539668dd20/R/stat_contour_fill.R#L47)) so I'm not sure why the need for the convoluted implementation. It's probably got to do with some subtlety I'm not grasping. 

We might have to ask @mjskay what's that all about and see if we can find a joint fix.

**Comment by mjskay** [comment]
Hmm let me take a look. That was a kludgey workaround for something when I wrote it and its possible it was a kludgey workaround for me not understanding all of the internals of geoms properly. The solution may be for me to fix lineribbon.

**Comment by mjskay** [comment]
Alright, I *think* the github version of tidybayes now fixes this problem **for stats only**. 

E.g. this example:

```r
set.seed(1234)
tb <- 
  tibble(time = 0:100) %>%
  group_by_all() %>%
  do(tibble(value = rnorm(100, .$time, 10)))

gg <- 
  tb %>%
  ggplot() +
  stat_lineribbon(aes(x = time, y = value)) +
  scale_fill_brewer()
gg
```
![image](https://user-images.githubusercontent.com/6345019/61178659-449d3200-a5bf-11e9-8bec-9679b3642ba9.png)

```r
gg + 
  ggnewscale::new_scale_fill() + 
  geom_point(dat = data.frame(x = runif(100,0,100), y = runif(100,0,100),
    fill = sample(1:4, 100, replace = TRUE)), aes(x = x, y = y, fill = fill), pch = 21
  )
```
![image](https://user-images.githubusercontent.com/6345019/61178662-4e269a00-a5bf-11e9-8cba-ee40dcab2708.png)


However, it still does not work for `geom_lineribbon` (and presumably other geoms in tidybayes that do what geom_lineribbon does). The problem is that I can't use `default_aes` with geoms to pull out pre-determined columns from the input data. For example, `geom_lineribbon` will pull out (by default, unless overridden by the user) the `.lower`, `.upper`, and `.width` columns from an input data frame to specify the `ymin`, `ymax`, and `fill` aesthetics. I'll admit this is a slightly unorthodox design decision---which I would maybe reconsider if writing the package again---but now that it's implemented and has users I am somewhat obligated to support it. 

I did look into the "canonical" way to do this and re-wrote the approach now used in the dev version of tidybayes. So for as I can tell `ggplot2::geom_sf` has a similar problem, and uses the `setup_layer` function of its layer to pull out the corresponding column. As a result, I rewrote the geoms in tidybayes that provide default aesthetics pulled from the input data to also use `setup_layer`. However, that did not fix the problem with `ggnewscale` on those geoms. I'm wondering if you might need to put a hook into `setup_layer` in ggnewscale somewhere?

Here's an example of the geom failing:

```r
set.seed(1234)
tb <- 
  tibble(time = 0:100) %>%
  group_by_all() %>%
  do(tibble(value = rnorm(100, .$time, 10))) %>%
  median_qi(value, .width = c(.50, .80, .95))

gg <- 
  tb %>%
  ggplot() +
  # while not specified, geom_lineribbon will fill in ymin, ymax, and fill 
  # based on .lower, .upper, and .width
  geom_lineribbon(aes(x = time, y = value)) +
  scale_fill_brewer()

gg
```
![image](https://user-images.githubusercontent.com/6345019/61178721-bb86fa80-a5c0-11e9-8639-5e9cf0c2062d.png)


```r
gg + 
  ggnewscale::new_scale_fill() + 
  geom_point(
    dat = data.frame(x = runif(100,0,100), y = runif(100,0,100),
    fill = sample(1:4, 100, replace = TRUE)), aes(x = x, y = y, fill = fill), pch = 21
  )
```
```
Error: Continuous value supplied to discrete scale
```

**Comment by eliocamp** [comment]
> I'm wondering if you might need to put a hook into setup_layer in ggnewscale somewhere?

Yep, absolutely. I'll look into that.

**Comment by eliocamp** [comment]
From what I'm seeing, `setup_layer()` is used by the special `LayerSf` class so I don't know if it would it be usable with any other geom.

**Comment by eliocamp** [comment]
I've noticed that if you define `geom_lineribbon()`thus:

```r 
geom_lineribbon <- function(mapping = aes(ymin = .lower, ymax = .upper, fill = forcats::fct_rev(ordered(.width))),
                            data = NULL,
                            stat = "identity", position = "identity",
                            ...,
                            na.rm = FALSE,
                            show.legend = NA,
                            inherit.aes = TRUE) {
  l = layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomLineribbon,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      na.rm = na.rm,
      ...
    )
  )
}
```


Then it works (albeit the legend shows the name). 

![image](https://user-images.githubusercontent.com/8617595/61243155-bbe8d800-a71d-11e9-9cd9-124f655312b9.png)

And ggnewscale has no issues.

**Comment by mjskay** [comment]
oh yeah, that makes sense! I updated to something similar but which still allows people to specify geom-specific aesthetics that fall back to the built-in defaults. I tested on ggnewscale and it seems to work. Thanks for the help!

**Comment by eliocamp** [comment]
Excellent! I run the previous example and it works perfectly.

**Comment by willgearty** [comment]
Wonderful, thank you both!
